### ISSUE TITLE
 Question about style of coding

### ISSUE THREAD

**Issue by MohammadMirsafaei** [restuwahyu13/gin-rest-api#2]
Hi. I was wondering if there is a reason why you handled return values most of the times using `channels`? Is this a best practice or personal preference?

**Comment by restuwahyu13** [comment]
@MohammadMirsafaei good question, this is style for personal preference not best practice, alternative you can use `instance variable` or `struct` for store your error, if you don't want to use `channels`

**Comment by MohammadMirsafaei** [comment]
That was helpful, thanks!
